/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package topsis;

/**
 *
 * @author Federico
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMDatos = new javax.swing.JMenu();
        jMElegirDatos = new javax.swing.JMenu();
        JMEntradaManual = new javax.swing.JMenuItem();
        JMImportar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMDatos.setText("Datos");

        jMElegirDatos.setText("Elegir Datos");

        JMEntradaManual.setText("Entrada Manual");
        JMEntradaManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMEntradaManualActionPerformed(evt);
            }
        });
        jMElegirDatos.add(JMEntradaManual);

        JMImportar.setText("Importar Desde Excel");
        JMImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMImportarActionPerformed(evt);
            }
        });
        jMElegirDatos.add(JMImportar);

        jMDatos.add(jMElegirDatos);

        jMenuBar1.add(jMDatos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMEntradaManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMEntradaManualActionPerformed
    CargarDatos cargarDatos = new CargarDatos();
    cargarDatos.setVisible(true);
    }//GEN-LAST:event_JMEntradaManualActionPerformed

    private void JMImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMImportarActionPerformed
       importar_excel importar = new importar_excel();
       importar.CrearTabla();
       importar.transformarObjetos(importar.alternativas, importar.matrizValores);
    }//GEN-LAST:event_JMImportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMEntradaManual;
    private javax.swing.JMenuItem JMImportar;
    private javax.swing.JMenu jMDatos;
    private javax.swing.JMenu jMElegirDatos;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
