/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package topsis;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Federico
 */
public class CargarDatos extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    DefaultTableModel modeloCriterio;
    DefaultTableModel modeloAlt;
    ArrayList <Criterio>listaCriterio;
    ArrayList<Alternativa>listaAlternativa;
    private static int d; 
    private double pesoTotal;
    public CargarDatos() {
        initComponents();   
        d=0;
        pesoTotal=0;
        modeloCriterio = (DefaultTableModel)this.tablaCriterio.getModel();
        if(tablaCriterio.getRowCount()!=0)
            this.btnEliminarCriterio.setEnabled(true);
        modeloAlt = (DefaultTableModel)this.tablaAlt.getModel();
        if(tablaAlt.getRowCount()!=0)
            this.btnEliminarAlternativa.setEnabled(true);
        listaCriterio=new ArrayList<Criterio>();
        listaAlternativa=new ArrayList<Alternativa>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotonCriterio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCriterio = new javax.swing.JTextField();
        txtPesoCriterio = new javax.swing.JTextField();
        rbtMax = new javax.swing.JRadioButton();
        rbtMin = new javax.swing.JRadioButton();
        btnAgregarCriterio = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCriterio = new javax.swing.JTable();
        btnEliminarCriterio = new javax.swing.JButton();
        lblPeso = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnAgregarAlternativa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlt = new javax.swing.JTable();
        btnEliminarAlternativa = new javax.swing.JButton();
        txtAlternativa = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TOPSIS SOLUTIONS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Criterios"));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Nombre de Criterio");

        jLabel2.setText("Peso de Criterio");

        jLabel3.setText("Tipo ");

        txtNombreCriterio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreCriterioKeyReleased(evt);
            }
        });

        txtPesoCriterio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesoCriterioKeyReleased(evt);
            }
        });

        grupoBotonCriterio.add(rbtMax);
        rbtMax.setText("Maximizar");

        grupoBotonCriterio.add(rbtMin);
        rbtMin.setText("Minimizar");

        btnAgregarCriterio.setText("Agregar");
        btnAgregarCriterio.setEnabled(false);
        btnAgregarCriterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCriterioActionPerformed(evt);
            }
        });

        tablaCriterio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Criterio", "Peso", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(tablaCriterio);

        btnEliminarCriterio.setText("Eliminar Criterio");
        btnEliminarCriterio.setEnabled(false);
        btnEliminarCriterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCriterioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtMin)
                            .addComponent(rbtMax)
                            .addComponent(txtPesoCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarCriterio)
                    .addComponent(btnAgregarCriterio))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPeso)
                .addGap(256, 256, 256))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPesoCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnAgregarCriterio)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtMax))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtMin)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEliminarCriterio)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblPeso)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Alternativas"));

        jLabel4.setText("Nombre de Alternativa");

        btnAgregarAlternativa.setText("Agregar");
        btnAgregarAlternativa.setEnabled(false);
        btnAgregarAlternativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlternativaActionPerformed(evt);
            }
        });

        tablaAlt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alternativa"
            }
        ));
        jScrollPane1.setViewportView(tablaAlt);

        btnEliminarAlternativa.setText("EliminarAlternativa");
        btnEliminarAlternativa.setEnabled(false);
        btnEliminarAlternativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlternativaActionPerformed(evt);
            }
        });

        txtAlternativa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAlternativaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlternativa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnAgregarAlternativa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEliminarAlternativa)
                        .addGap(56, 56, 56)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtAlternativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnAgregarAlternativa)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarAlternativa)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(311, 311, 311)
                                .addComponent(btnSiguiente)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSiguiente)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCriterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCriterioActionPerformed
        
       
        try{
            Double peso=Double.parseDouble(this.txtPesoCriterio.getText());
            Criterio c=new Criterio(this.txtNombreCriterio.getText(),peso,getTipo());
            pesoTotal+=peso;
        
        
        String tipo;
        if(c.getTipo()==0)
            tipo="Minimizar";
        else
            tipo="Maximizar";
        String [] datos ={c.getNombre(),Double.toString(c.getPeso()),tipo};
        modeloCriterio.addRow(datos);
        listaCriterio.add(c);
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Datos mal cargados", "error", JOptionPane.ERROR_MESSAGE);
       
            System.out.println(e.getMessage());
        }
        this.txtNombreCriterio.setText(null);
        this.txtPesoCriterio.setText(null);        
        this.refrescarBotones();
        
        
    }//GEN-LAST:event_btnAgregarCriterioActionPerformed

    private void btnEliminarCriterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCriterioActionPerformed
        if(tablaCriterio.getSelectedRow()> -1 )
        {
            for (int i=0;i<listaCriterio.size();i++)
                if(tablaCriterio.getValueAt(tablaCriterio.getSelectedRow(),0).toString().compareTo(listaCriterio.get(i).getNombre())==0)
                {
                    pesoTotal-=listaCriterio.get(i).getPeso();
                    listaCriterio.remove(i);
                }    
            
            modeloCriterio.removeRow(tablaCriterio.getSelectedRow());
            
        }
        else
            JOptionPane.showMessageDialog(this, "Seleccione un criterio","Error",JOptionPane.ERROR_MESSAGE);
        
        this.refrescarBotones();
    }//GEN-LAST:event_btnEliminarCriterioActionPerformed

    private void btnAgregarAlternativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlternativaActionPerformed
       
        d++;
       Alternativa a=new Alternativa(txtAlternativa.getText());              
        String [] datos={this.txtAlternativa.getText()} ;
        modeloAlt.addRow(datos);
        listaAlternativa.add(a);
        this.txtAlternativa.setText(null);
        this.refrescarBotones();
    }//GEN-LAST:event_btnAgregarAlternativaActionPerformed

    private void btnEliminarAlternativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlternativaActionPerformed
        if(tablaAlt.getSelectedRow()> -1)
        { 
            for(int i=0;i<listaAlternativa.size();i++) {
                if(tablaAlt.getValueAt(tablaAlt.getSelectedRow(),0).toString().compareTo(listaAlternativa.get(i).getNombre())==0)
                listaAlternativa.remove(i);                
            }
        modeloAlt.removeRow(tablaAlt.getSelectedRow());
        }
        else
            JOptionPane.showMessageDialog(this,"Seleccione una alternativa", "Error", JOptionPane.ERROR_MESSAGE);
       this.refrescarBotones();
    }//GEN-LAST:event_btnEliminarAlternativaActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        cargarMatriz pan=new cargarMatriz(listaCriterio,listaAlternativa);
        pan.setVisible(true);
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void txtPesoCriterioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoCriterioKeyReleased
        this.refrescarBotones();
    }//GEN-LAST:event_txtPesoCriterioKeyReleased

    private void txtNombreCriterioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCriterioKeyReleased
        this.refrescarBotones();
    }//GEN-LAST:event_txtNombreCriterioKeyReleased

    private void txtAlternativaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlternativaKeyReleased
        this.refrescarBotones();
    }//GEN-LAST:event_txtAlternativaKeyReleased

    private int getTipo()
    {
        String aux="";
        int tipo=0;
        for (Enumeration e = this.grupoBotonCriterio.getElements(); e.hasMoreElements();) {
        JRadioButton b = (JRadioButton) e.nextElement();
        if (b.getModel() == grupoBotonCriterio.getSelection()) {
        aux= b.getText();
      }
        if(aux.compareTo("Maximizar")==0)
        tipo=1;
    }
        return tipo;
        
    }
    private void refrescarBotones()
    {
        if(!(this.txtPesoCriterio.getText().isEmpty()) && !(this.txtNombreCriterio.getText().isEmpty()))
        {
            this.btnAgregarCriterio.setEnabled(true);
        }
        else
        {
            this.btnAgregarCriterio.setEnabled(false);
        }
       
        if(tablaCriterio.getRowCount()==0)
         this.btnEliminarCriterio.setEnabled(false);
        else
            this.btnEliminarCriterio.setEnabled(true);
        
        if(!this.txtAlternativa.getText().isEmpty())
            this.btnAgregarAlternativa.setEnabled(true);
        else
            this.btnAgregarAlternativa.setEnabled(false);
        
         if(tablaAlt.getRowCount()==0)
            this.btnEliminarAlternativa.setEnabled(false);
         else
             this.btnEliminarAlternativa.setEnabled(true);
         
         grupoBotonCriterio.clearSelection();
         this.lblPeso.setText("El peso faltante es " + (1-pesoTotal));
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarDatos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAlternativa;
    private javax.swing.JButton btnAgregarCriterio;
    private javax.swing.JButton btnEliminarAlternativa;
    private javax.swing.JButton btnEliminarCriterio;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.ButtonGroup grupoBotonCriterio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JRadioButton rbtMax;
    private javax.swing.JRadioButton rbtMin;
    private javax.swing.JTable tablaAlt;
    private javax.swing.JTable tablaCriterio;
    private javax.swing.JTextField txtAlternativa;
    private javax.swing.JTextField txtNombreCriterio;
    private javax.swing.JTextField txtPesoCriterio;
    // End of variables declaration//GEN-END:variables
}
